# Generated by Django 5.2.6 on 2025-09-29 09:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_auth_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.FileField(
                blank=True, null=True, upload_to=users.models.user_image_path
            ),
        ),
    ]
