# Generated by Django 5.2.6 on 2025-09-26 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Ma'), ('Female', 'Fe')], max_length=15, null=True)),
                ('status', models.CharField(choices=[('Available', 'Av'), ('Pending', 'Pe'), ('Adopted', 'Ad')], default='Available', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('adoption_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccines', models.ManyToManyField(blank=True, to='vaccines.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_unsigned_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet')),
            ],
        ),
    ]
