# Generated by Django 5.2.6 on 2025-09-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petimage',
            name='image_unsigned_url',
        ),
        migrations.AddField(
            model_name='petimage',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
    ]
