# Generated by Django 5.2.6 on 2025-09-30 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_petimage_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pets.pet'),
        ),
    ]
