# Generated by Django 5.2.6 on 2025-09-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdoptionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pe"),
                            ("Approved", "Ap"),
                            ("Rejected", "Re"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("requested_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
