# Generated by Django 5.2.6 on 2025-09-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adoptions", "0001_initial"),
        ("pets", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionapplication",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pets.pet"
            ),
        ),
        migrations.AddField(
            model_name="adoptionapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
    ]
