# Generated by Django 5.2.6 on 2025-10-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0002_alter_adoptionapplication_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptionapplication",
            name="has_other_pets",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adoptionapplication",
            name="home_ownership",
            field=models.CharField(
                choices=[("Own", "Own"), ("Rent", "Rent")], default="Own", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="adoptionapplication",
            name="housing_type",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Apartment", "Apartment"),
                    ("Condo", "Condo"),
                    ("Other", "Other"),
                ],
                default="House",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="adoptionapplication",
            name="other_pets_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adoptionapplication",
            name="work_schedule",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="adoptionapplication",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Why do you want to adopt this pet?"
            ),
        ),
    ]
