# Generated by Django 5.2.6 on 2025-10-03 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0003_adoptionapplication_has_other_pets_and_more"),
        ("users", "0005_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoptionapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
    ]
